name: stencil-action
description: Github Action for interacting with stencil
author: Jared Allard <@jaredallard>

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'book'
  color: 'yellow'

# Define your inputs here.
inputs:
  github-token:
    description: 'Unused. stencil is downloaded from bins.rgst.io'
    deprecationMessage:
      'github-token is no longer used, stencil is downloaded from bins.rgst.io.
      It can be removed.'

  version:
    description: >
      The version of stencil to use. 'latest' resolves the latest version from
      bins.rgst.io
    default: 'latest'

  binary-dir:
    description: 'The directory to store the binary in'
    default: '~/.local/bin'

  prereleases:
    description: >
      Whether to consider prereleases or not when resolving 'latest' (uses
      LATEST_PRERELEASE instead of LATEST on bins.rgst.io)
    default: 'false'

runs:
  using: node24
  main: dist/index.js
