name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          persist-credentials: false

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version-file: .node-version
          cache: yarn

      - name: Install Dependencies
        id: install
        run: corepack enable && corepack install && yarn --immutable

      - name: Check Format
        run: yarn run format:check

      - name: Lint
        run: yarn run lint

      - name: Test
        run: yarn run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          persist-credentials: false

      - name: Install Stencil
        id: test-action
        uses: ./
        with:
          github-token: ${{ github.token }}
          version: 'latest'
          binary-dir: '~/.local/bin'
          prereleases: true

      - name: Run Stencil
        id: test-action-run
        run: stencil --version
