name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version-file: .node-version

      - name: Install Dependencies
        run: corepack enable && corepack install && yarn --immutable

      - name: Check Format
        run: yarn run format:check

      - name: Lint
        run: yarn run lint

      - name: Test
        run: yarn run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      ## Latest
      - name: can install latest
        uses: ./
        with:
          github-token: ${{ github.token }}
          version: 'latest'
          binary-dir: '~/.local/bin'
          prereleases: true

      ## Forgejo
      - name: can install from forgejo
        uses: ./
        with:
          github-token: ${{ github.token }}
          version: '2.19.0-rc.1'
          binary-dir: '~/.local/bin'

      ## Github
      - name: can install from github
        uses: ./
        with:
          github-token: ${{ github.token }}
          version: '2.18.0'
          binary-dir: '~/.local/bin'

      ## Was in path
      - run: stencil --version
